export type AuditReasonCode =
  | "CHAT_MESSAGE"
  | "GUARDRAIL_TRIGGERED"
  | "PII_DETECTED"
  | "RATE_LIMIT_EXCEEDED"
  | "LEAD_CAPTURED"
  | "ESCALATED_TO_HUMAN"
  | "SYSTEM_ERROR"
  | "RETRIEVAL_ABUSE_BLOCKED"
  | "RETRIEVAL_PERFORMED"
  | "INTERNAL_CONTENT_LEAK_BLOCKED"
  | "SLA_BREACHED"
  | "ROUTING_OVERRIDDEN";
